# Generated by Django 3.0.1 on 2021-08-04 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210803_2003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
